### ISSUE TITLE
关于blog的进一步优化的实现

### ISSUE THREAD

**Issue by alexanderliu-creator** [OrangePure/OrangePure.github.io#1]
**猫仔亮你好哈哈哈，关于blog的优化，我看到了有学长成功做出了优化的动画小人，放在sidebar的右下角，并且动画小人的目光会随着鼠标的移动而移动，想问下亮亮有没有做出这一类的东西，或是有没有什么资源能实现这样的优化。**

**Comment by OrangePure** [comment]
淦，才看到，怎么博客都上不了了
